# Brain Rot Project - Data Cleaning

## 0. Import Libraries and Load Raw Data

In [3]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 200)

# Load the original (raw) csv files
path = r"F:\Data Analysis\DEPI\Final Final Project\Depi-Data-Analysis-Project(github project structure)\raw_data"

fact = pd.read_csv(f"{path}/Fact_User_Activity.csv")
users = pd.read_csv(f"{path}/Dim_Users.csv")
habits = pd.read_csv(f"{path}/Dim_Habits.csv")
mentalstate = pd.read_csv(f"{path}/Dim_MentalState.csv")
date = pd.read_csv(f"{path}/Dim_Date.csv")

print("All files loaded successfully!")

All files loaded successfully!

## 1. Cleaning Fact_User_Activity

In [4]:
# Step 1: check missing values
print("Missing values before cleaning:")
print(fact.isnull().sum())

Missing values before cleaning:
ActivityID                  0
UserKey                     0
DateKey                     0
StateKey                    0
HabitKey                    0
Study_Hours                 0
Coffee_Consumed_Per_Day     0
Smoking_Breaks_Count        0
Total_Reels_Watched         0
Short_Content_Percentage    0
Peak_Hour                   0
Focus_Sessions_Count        0
Brainrot_Exposure_Score     0
Wellbeing_Score             0
dtype: int64

In [5]:
# Step 2: check duplicated rows
print("Duplicated rows :", fact.duplicated().sum())

Duplicated rows : 0

In [ ]:
# Step 3: check for impossible values in the important numeric columns
# Importante !!!! (a value is "impossible" if it is negative, when negative does not make sense)

print("Minimum Study_Hours:", fact['Study_Hours'].min())
print("Minimum Coffee_Consumed_Per_Day:", fact['Coffee_Consumed_Per_Day'].min())
print("Minimum Smoking_Breaks_Count:", fact['Smoking_Breaks_Count'].min())
print("Minimum Total_Reels_Watched:", fact['Total_Reels_Watched'].min()) 
print("Minimum Focus_Sessions_Count:", fact['Focus_Sessions_Count'].min())
print("Minimum Brainrot_Exposure_Score:", fact['Brainrot_Exposure_Score'].min())
print("Minimum Wellbeing_Score:", fact['Wellbeing_Score'].min())

Minimum Study_Hours: 0.0
Minimum Coffee_Consumed_Per_Day: 0
Minimum Smoking_Breaks_Count: 0
Minimum Total_Reels_Watched: 2
Minimum Focus_Sessions_Count: 0
Minimum Brainrot_Exposure_Score: 0.0
Minimum Wellbeing_Score: 0.0

In [7]:
# Step 4: check data types are correct
print(fact.dtypes)

ActivityID                    int64
UserKey                       int64
DateKey                       int64
StateKey                      int64
HabitKey                      int64
Study_Hours                 float64
Coffee_Consumed_Per_Day       int64
Smoking_Breaks_Count          int64
Total_Reels_Watched           int64
Short_Content_Percentage    float64
Peak_Hour                     int64
Focus_Sessions_Count          int64
Brainrot_Exposure_Score     float64
Wellbeing_Score             float64
dtype: object

In [8]:
fact_clean = fact.copy()
print("Fact_User_Activity is now clean. Shape:", fact_clean.shape)

Fact_User_Activity is now clean. Shape: (5000, 14)

## 2. Cleaning Dim_Users

In [9]:
print("Missing values before cleaning:")
print(users.isnull().sum())

Missing values before cleaning:
UserKey             0
Username            0
Age                 0
Age_Group           0
Region              0
Device_Type         0
Is_Smoker           0
Base_Focus_Level    0
dtype: int64

In [ ]:
print("Duplicated rows :", users.duplicated().sum())

Duplicated rows : 0

In [ ]:
print("Minimum Age:", users['Age'].min())
print("Maximum Age:", users['Age'].max())

Minimum Age: 8
Maximum Age: 25

In [35]:
users_clean = users.copy()
print(users_clean.shape)

(99, 8)

## 3. Cleaning Dim_Habits

In [13]:
habits

   HabitKey Coffee_Level Smoking_Status
0         1          NaN     Non-Smoker
1         2     Moderate     Occasional
2         3       Addict   Heavy-Smoker

In [14]:
print("Missing values before cleaning:")
print(habits.isnull().sum())

Missing values before cleaning:
HabitKey          0
Coffee_Level      1
Smoking_Status    0
dtype: int64

In [ ]:
habits['Coffee_Level'] = habits['Coffee_Level'].fillna('Unknown')
print("Missing values after cleaning:")
print(habits.isnull().sum())

Missing values after cleaning:
HabitKey          0
Coffee_Level      0
Smoking_Status    0
dtype: int64

In [ ]:
print("Duplicated rows:", habits.duplicated().sum())
habits_clean = habits.copy()
habits_clean

Duplicated rows: 0

   HabitKey Coffee_Level Smoking_Status
0         1      Unknown     Non-Smoker
1         2     Moderate     Occasional
2         3       Addict   Heavy-Smoker

## 4. Cleaning Dim_MentalState

In [ ]:
print("Missing values:")
print(mentalstate.isnull().sum())
print("Duplicated rows:", mentalstate.duplicated().sum())
mentalstate_clean = mentalstate.copy()
mentalstate_clean

Missing values:
StateKey                0
Attention_Span_Level    0
Brainrot_Stage          0
Aura_Color_Code         0
dtype: int64
Duplicated rows: 0

   StateKey Attention_Span_Level Brainrot_Stage Aura_Color_Code
0         1                 High        Healthy           Green
1         2               Medium         Casual          Yellow
2         3               Cooked       Advanced             Red
3         4                Fried       Critical             Red

## 5. Cleaning Dim_Date

This table has one row per calendar day. We convert `FullDate` from text to a real date type.

In [ ]:
print("Missing values before cleaning:")
print(date.isnull().sum())
print("Duplicated rows:", date.duplicated().sum())

Missing values before cleaning:
DateKey           0
FullDate          0
Is_Late_Night     0
Is_Exam_Season    0
Is_Weekend        0
dtype: int64
Duplicated rows: 0

In [34]:
print("Data type before conversion:", date['FullDate'].dtype)
date['FullDate'] = pd.to_datetime(date['FullDate'])
print(date['FullDate'].dtype)

Data type before conversion: datetime64[ns]
datetime64[ns]

In [33]:
date_clean = date.copy()
print(date_clean.shape)
date_clean.head()

(365, 5)

    DateKey   FullDate  Is_Late_Night  Is_Exam_Season  Is_Weekend
0  20260101 2026-01-01              0               1           0
1  20260102 2026-01-02              0               1           1
2  20260103 2026-01-03              0               1           1
3  20260104 2026-01-04              1               1           0
4  20260105 2026-01-05              0               1           0

## 6. Checking Relationships Between Tables (Foreign Keys)

In [ ]:
users_not_found = fact_clean[~fact_clean['UserKey'].isin(users_clean['UserKey'])]
print("Number of fact rows with a UserKey that does NOT exist in Dim_Users:", len(users_not_found))

Number of fact rows with a UserKey that does NOT exist in Dim_Users: 51
Missing UserKey values: [100]

In [22]:
dates_not_found = fact_clean[~fact_clean['DateKey'].isin(date_clean['DateKey'])]
print("Number of fact rows with a DateKey that does NOT exist in Dim_Date:", len(dates_not_found))

Number of fact rows with a DateKey that does NOT exist in Dim_Date: 0

In [23]:
habits_not_found = fact_clean[~fact_clean['HabitKey'].isin(habits_clean['HabitKey'])]
print("Number of fact rows with a HabitKey that does NOT exist in Dim_Habits:", len(habits_not_found))

Number of fact rows with a HabitKey that does NOT exist in Dim_Habits: 0

In [24]:
states_not_found = fact_clean[~fact_clean['StateKey'].isin(mentalstate_clean['StateKey'])]
print("Number of fact rows with a StateKey that does NOT exist in Dim_MentalState:", len(states_not_found))

Number of fact rows with a StateKey that does NOT exist in Dim_MentalState: 0

## 7. Save the Cleaned CSV Files

In [ ]:
fact_clean.to_csv('Fact_User_Activity.csv', index=False)
users_clean.to_csv('Dim_Users.csv', index=False)
habits_clean.to_csv('Dim_Habits.csv', index=False)
mentalstate_clean.to_csv('Dim_MentalState.csv', index=False)
date_clean.to_csv('Dim_Date.csv', index=False)

All 5 cleaned files were saved successfully.

## 8. Full Join - Building the Final Merged Dataset

In [26]:
# Start from the fact table and add the users information
final_df = fact_clean.merge(users_clean, on='UserKey', how='left')
print("Shape after merging with Dim_Users:", final_df.shape)

Shape after merging with Dim_Users: (5000, 21)

In [27]:
final_df = final_df.merge(date_clean, on='DateKey', how='left')
print("Shape after merging with Dim_Date:", final_df.shape)

Shape after merging with Dim_Date: (5000, 25)

In [28]:
final_df = final_df.merge(habits_clean, on='HabitKey', how='left')
print("Shape after merging with Dim_Habits:", final_df.shape)

Shape after merging with Dim_Habits: (5000, 27)

In [29]:
final_df = final_df.merge(mentalstate_clean, on='StateKey', how='left')
print("Shape after merging with Dim_MentalState:", final_df.shape)

Shape after merging with Dim_MentalState: (5000, 30)

In [ ]:
final_df.to_csv('BrainRot_Final_Dataset.csv', index=False)

BrainRot_Final_Dataset.csv saved successfully.

## 9. Final Check on the Merged Dataset

In [31]:
print(final_df.shape)
final_df.head()

(5000, 30)

,ActivityID,UserKey,DateKey,StateKey,HabitKey,Study_Hours,Coffee_Consumed_Per_Day,Smoking_Breaks_Count,Total_Reels_Watched,Short_Content_Percentage,Peak_Hour,Focus_Sessions_Count,Brainrot_Exposure_Score,Wellbeing_Score,Username,Age,Age_Group,Region,Device_Type,Is_Smoker,Base_Focus_Level,FullDate,Is_Late_Night,Is_Exam_Season,Is_Weekend,Coffee_Level,Smoking_Status,Attention_Span_Level,Brainrot_Stage,Aura_Color_Code
0,1,90,20261008,4,2,5.4,1,9,198,0.75,16,3,94.82,20.18,User_90,18.0,Teen,Aswan,Smartphone,1.0,91.0,2026-10-08,1,0,0,Moderate,Occasional,Fried,Critical,Red
1,2,62,20260108,1,2,7.6,3,0,2,0.41,22,9,0.00,100.00,User_62,22.0,Young,Luxor,Tablet,0.0,93.0,2026-01-08,0,1,0,Moderate,Occasional,High,Healthy,Green
2,3,45,20260320,2,2,1.2,2,0,125,0.77,23,2,57.00,53.00,User_45,16.0,Teen,Port Said,Tablet,0.0,62.0,2026-03-20,0,0,1,Moderate,Occasional,Medium,Casual,Yellow
3,4,76,20261121,1,3,3.5,2,11,18,0.41,0,6,10.03,100.00,User_76,17.0,Teen,Alexandria,PC,1.0,89.0,2026-11-21,0,0,1,Addict,Heavy-Smoker,High,Healthy,Green
4,5,66,20260414,1,1,5.5,0,0,27,0.46,16,5,3.56,100.00,User_66,18.0,Teen,Mansoura,Smartphone,0.0,67.0,2026-04-14,0,0,0,Unknown,Non-Smoker,High,Healthy,Green

In [32]:
print(final_df.isnull().sum())

ActivityID                   0
UserKey                      0
DateKey                      0
StateKey                     0
HabitKey                     0
Study_Hours                  0
Coffee_Consumed_Per_Day      0
Smoking_Breaks_Count         0
Total_Reels_Watched          0
Short_Content_Percentage     0
Peak_Hour                    0
Focus_Sessions_Count         0
Brainrot_Exposure_Score      0
Wellbeing_Score              0
Username                    51
Age                         51
Age_Group                   51
Region                      51
Device_Type                 51
Is_Smoker                   51
Base_Focus_Level            51
FullDate                     0
Is_Late_Night                0
Is_Exam_Season               0
Is_Weekend                   0
Coffee_Level                 0
Smoking_Status               0
Attention_Span_Level         0
Brainrot_Stage               0
Aura_Color_Code              0
dtype: int64